// <auto-generated />
using System;
using EMS.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EMS.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260417042207_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EMS.API.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PasswordHash = "$2a$11$aOF0.jF2lRGmNwy4lJDpaO41YxEtkwl9YPf89JN9klHgnORCgbY1u",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PasswordHash = "$2a$11$RM0rrGd1zhGfEdLrInBBmuzU8dmwRYoq0ibYZ4e.HNkfUvdbTq4EK",
                            Role = "Viewer",
                            Username = "viewer"
                        });
                });

            modelBuilder.Entity("EMS.API.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal>("Salary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2022, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Engineering",
                            Designation = "Software Engineer",
                            Email = "umeshreddy@gmail.com",
                            FirstName = "Umesh",
                            JoinDate = new DateTime(2022, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Reddy",
                            Phone = "9876543210",
                            Salary = 750000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2022, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Marketing",
                            Designation = "Marketing Executive",
                            Email = "vinuhyakolisetty@gmail.com",
                            FirstName = "Vinuhya",
                            JoinDate = new DateTime(2021, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Kolisetty",
                            Phone = "9876543211",
                            Salary = 550000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2021, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2020, 11, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "HR",
                            Designation = "HR Executive",
                            Email = "pravallikanaidu@gmail.com",
                            FirstName = "Pravallika",
                            JoinDate = new DateTime(2020, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Naidu",
                            Phone = "9876543212",
                            Salary = 500000m,
                            Status = "Inactive",
                            UpdatedAt = new DateTime(2020, 11, 20, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2019, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Finance",
                            Designation = "Accountant",
                            Email = "lekhalekhana@gmail.com",
                            FirstName = "Lekhana",
                            JoinDate = new DateTime(2019, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Reddy",
                            Phone = "9876543213",
                            Salary = 650000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2019, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 1, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Operations",
                            Designation = "Operations Analyst",
                            Email = "kavyanair@gmail.com",
                            FirstName = "Kavya",
                            JoinDate = new DateTime(2023, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Nair",
                            Phone = "9876543214",
                            Salary = 600000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2023, 1, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2022, 9, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Engineering",
                            Designation = "Frontend Developer",
                            Email = "ashokashok12@gmail.com",
                            FirstName = "Ashok",
                            JoinDate = new DateTime(2022, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Reddy",
                            Phone = "9876543215",
                            Salary = 720000m,
                            Status = "Inactive",
                            UpdatedAt = new DateTime(2022, 9, 18, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2021, 12, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Marketing",
                            Designation = "SEO Specialist",
                            Email = "sunilyadav@gmail.com",
                            FirstName = "Sunil",
                            JoinDate = new DateTime(2021, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Yadav",
                            Phone = "9876543216",
                            Salary = 530000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2021, 12, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "HR",
                            Designation = "Talent Acquisition Specialist",
                            Email = "rachanayadav@gmail.com",
                            FirstName = "Rachana",
                            JoinDate = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Yadav",
                            Phone = "9876543217",
                            Salary = 580000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2023, 5, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Finance",
                            Designation = "Financial Analyst",
                            Email = "karthikkarthik123@gmail.com",
                            FirstName = "Karthik",
                            JoinDate = new DateTime(2023, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Reddy",
                            Phone = "9876543218",
                            Salary = 800000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2023, 5, 30, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2018, 7, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Operations",
                            Designation = "Operations Manager",
                            Email = "sureshkumar@gmail.com",
                            FirstName = "Suresh",
                            JoinDate = new DateTime(2018, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Kumar",
                            Phone = "9876543219",
                            Salary = 900000m,
                            Status = "Inactive",
                            UpdatedAt = new DateTime(2018, 7, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2022, 2, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Engineering",
                            Designation = "Backend Developer",
                            Email = "divyarao@gmail.com",
                            FirstName = "Divya",
                            JoinDate = new DateTime(2022, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Rao",
                            Phone = "9876543220",
                            Salary = 780000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2022, 2, 11, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2021, 6, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Marketing",
                            Designation = "Content Strategist",
                            Email = "kiranpillai@gmail.com",
                            FirstName = "Kiran",
                            JoinDate = new DateTime(2021, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Pillai",
                            Phone = "9876543221",
                            Salary = 560000m,
                            Status = "Inactive",
                            UpdatedAt = new DateTime(2021, 6, 19, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2019, 10, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "HR",
                            Designation = "HR Manager",
                            Email = "nehakapoor@gmail.com",
                            FirstName = "Neha",
                            JoinDate = new DateTime(2019, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Kapoor",
                            Phone = "9876543222",
                            Salary = 850000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2019, 10, 8, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2020, 1, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Finance",
                            Designation = "Finance Manager",
                            Email = "adityasingh@gmail.com",
                            FirstName = "Aditya",
                            JoinDate = new DateTime(2020, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Singh",
                            Phone = "9876543223",
                            Salary = 950000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2020, 1, 17, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2023, 9, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Operations",
                            Designation = "Logistics Coordinator",
                            Email = "poojachauhan@gmail.com",
                            FirstName = "Pooja",
                            JoinDate = new DateTime(2023, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Chauhan",
                            Phone = "9876543224",
                            Salary = 520000m,
                            Status = "Active",
                            UpdatedAt = new DateTime(2023, 9, 9, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
